from typing import List, Optional

from qarp.blocks._block import AnyBlock
from qarp.blocks._composite_block import CompositeBlock
from qarp.blocks._primitives.synthesized_unitary_block import SynthesizedUnitaryBlock
from qarp.blocks._state_preparation.computational_basis_state_block import (
    ComputationalBasisStateBlock,
)
from qarp.endianness import msb_to_lsb_matrix
from qarp.operators._vumpo import VUMPO  # the package re-exports it lazily; mypy needs the source


class VUMPOBrickworkBlock(CompositeBlock):
    def __init__(
        self,
        vumpo: VUMPO,
        initial_state=None,
        optimized_params=None,
        target_qubits: Optional[List[int]] = None,
        name: str = "VUMPOBrickworkBlock",
    ):
        r"""
        Constructs a circuit block implementing a Variational Unitary Matrix Product
        Operator (VUMPO) ansatz from
        - F. Pollmann, V. Khemani, J. Ignacio Cirac, and S. L. Sondhi,
            Efficient variational diagonalization of fully many-body localized Hamiltonians
            Phys. Rev. B 94, 041116(R).


        This block provides a gate-level realization of a VUMPO as described in the above reference.
        A VUMPO (brickwork) layer consists of a sequence of nearest-neighbour two‑qubit unitaries arranged in
        a brickwork pattern. Each gate is generated by the ``VUMPO`` object via its internal parameterization,
        typically corresponding to a unitary tensor with a small bond dimension.

        If no ``optimized_params`` are supplied, the block invokes ``vumpo.build()`` to
        generate a full parameter vector for the gate unitaries. For each layer, gates are placed on
        qubit pairs ``(n, n+1)`` starting from offset ``m % 2``.

        **Assumptions**
          - ``vumpo.L`` specifies the number of physical qubits.
          - ``vumpo.build_gate(params)`` returns a valid two‑qubit unitary matrix.
          - ``optimized_params`` has length exactly
                ``vumpo.n_gates * vumpo.params_per_gate`` (``ValueError`` otherwise)
            matching the brickwork pattern.

        Args:
            vumpo: A ``VUMPO`` object defining the brickwork structure, number of
                layers, qubit count, and per‑gate parameterization.
            initial_state: Optional occupation vector used to prepend a computational
                basis state block.
            optimized_params: Optional flat parameter array. If ``None``, the block
                calls ``vumpo.build()`` to generate parameters.
            target_qubits: Specific qubits to apply the block to. If None, uses all qubits.
            name: Optional custom name for the block.

        """

        if optimized_params is None:
            optimized_params = vumpo.build()
        self.n_layers = vumpo.n_layers
        n_qubits = vumpo.L
        self.blocks: list[AnyBlock] = []

        if initial_state is not None:
            initial_state_block = ComputationalBasisStateBlock(initial_state)
            self.blocks += [initial_state_block]

        # layerise_params owns the tiling and the exact-length check, so the
        # circuit emitted here cannot drift from the network the parameters
        # were optimised on.
        for m, layer in enumerate(vumpo.layerise_params(optimized_params)):
            for n, p in layer:
                # quimb -> qarpx boundary: build_gate is in quimb's site order
                # (site 0 = leftmost kron factor); the block wants qarpx LSB.
                gate = msb_to_lsb_matrix(vumpo.build_gate(p))
                target_qubits_per_tens = [n, n + 1]
                self.blocks += [
                    SynthesizedUnitaryBlock(
                        gate,
                        target_qubits=target_qubits_per_tens,
                        name=f"L{m}-G{n}",
                    )
                ]

        super().__init__(
            blocks=self.blocks,
            n_qubits=n_qubits,
            target_qubits=target_qubits,
            name=name,
        )
